[package]
name = "RepoToTestRS"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.3"
glob = "0.3.1"
rust_tree = "0.1.4"
walkdir = "2.5.0"
