[package]
    edition="2021"
    name="repo_to_txt"
    version="0.1.0"

    # See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
    clap="4.5.3"
    glob-match="0.2.1"
    rust_tree="0.1.4"
    walkdir="2.5.0"
