# config.toml

# Exclude globs for the tree command
tree_exclude_globs="node_modules|.git|target|dist|build"

# Ignore files and directories matching these patterns
ignore_files=["*.bak", "*.log", "*.tmp", "temp/", "test_data/"]

# File extensions to include
file_extensions=["json", "md", "rs", "toml", "txt", "yaml", "yml"]
