base_exclude_globs=[
    "**/*.env**",
    "**/node_modules/**",
    "*.prettierignore",
    ".git/**",
    "build/**",
    "dist/**",
    "out",
    "package-lock.json",
    "target/**",
]
base_include_globs=["**/*.js", "**/*.ts", "**/*.tsx"]
enable_gitignore=false
tree_exclude_globs="node_modules|build|_locales|.plasmo|locales"
